---
# Credentials for EOS Switches
ansible_user: arista
ansible_password: "{{ (lookup('file', '/home/coder/.config/code-server/config.yaml', errors='ignore') | from_yaml).password | default(lookup('ansible.builtin.env', 'LABPASSPHRASE')) }}"
ansible_network_os: arista.eos.eos
# Configure privilege escalation
ansible_become: true
ansible_become_method: enable
# HTTPAPI configuration
ansible_connection: httpapi
ansible_httpapi_port: 443
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
ansible_python_interpreter: $(which python3)

# arista.avd.cv_deploy role parameters
# Export token using 'export CV_TOKEN=<generated token here>'
cv_token: "{{ lookup('env', 'CV_TOKEN') }}"
cv_server: cvp
cv_verify_certs: false

# TerminAttr settings
cv_settings:
  onprem_clusters:
    - name: atd-cvp
      servers:
        - name: 192.168.0.5
  terminattr:
    disable_aaa: true

# Login Banner
custom_structured_configuration_banners:
  motd: |
    You shall not pass. Unless you are authorized. Then you shall pass.
    EOF

# Aliases
custom_structured_configuration_aliases:
  |
    alias al show running-config | include alias
    alias bem show bgp evpn route mac-ip
    alias ber show bgp evpn
    alias bes show bgp evpn summary
    alias bf sho bfd peers
    alias bk show ip bgp neighbor | i or is|keepalive
    alias bn show ip bgp neighbor
    alias br show ip bgp regex
    alias bra show ip bgp regex _3458_
    alias bs show ip bgp summary
    alias bt show ip bgp
    alias cc config checkpoint save
    alias ch show history
    alias ct conf t
    alias dc delete checkpoint:
    alias ia show ip arp
    alias ib show ip interface brief
    alias id show interface description
    alias ii show ip interface brief
    alias in show isis neighbors
    alias ir show ip route
    alias is show ip interface | i Internet address
    alias it show inter trunk
    alias iu show ip interface brief | include up
    alias ln show lldp neighbor
    alias mb show mlag
    alias md show mlag | i down
    alias mp show mlag | i peer-link
    alias mu show mlag | i up
    alias oi show ip osp int bri
    alias on show ip ospf nei
    alias p ping
    alias p235 ping 199.5.47.235
    alias p8 ping 8.8.8.8
    alias pah ping 10.136.255.47
    alias par ping 10.133.0.250
    alias pb ping 10.144.190.254
    alias pbr ping 10.132.16.167
    alias pbt ping 10.144.190.100
    alias pc ping vrf Volkswagen-CBB
    alias pd show int des | i Po
    alias pf ping 10.186.44.80
    alias ph ping 10.138.2.254
    alias pht ping 10.138.2.100
    alias pp ping vrf PROD
    alias ps show port-channel brief
    alias pw ping 10.144.100.254
    alias pwb ping 10.186.44.80
    alias pwt ping 10.144.100.100
    alias rb show run | section router bgp
    alias ri show run int
    alias ro show run | sec router ospf
    alias sa show arp
    alias sc show config checkpoint
    alias si show int
    alias sis show interface status
    alias sm show mac address-table dymanic
    alias sp show management api http-commands
    alias sr show run
    alias srai show run all | inc
    alias sras show run all | sec
    alias sri show run | inc
    alias srs show run | sec
    alias ss show spanning-tree
    alias st show ip nat translation
    alias sv show version | i image
    alias t traceroute
    alias t235 traceroute 199.5.47.235
    alias t8 traceroute 8.8.8.8
    alias tah traceroute 10.136.255.47
    alias tar traceroute 10.133.0.250
    alias tb traceroute 10.144.190.254
    alias tbr traceroute 10.132.16.167
    alias tf traceroute 10.186.44.80
    alias th show interfaces transceiver hardware | i Name|Media
    alias tw traceroute 10.144.100.254
    alias twb traceroute 10.186.44.10
    alias ut show uptime
    alias va show vxlan address-table evpn
    alias vn show vxlan vni
    alias vt show vxlan vtep
    alias vx show interface vxlan1

# Syslog
logging_settings:
  hosts:
    - name: 10.200.0.108
    - name: 10.200.1.108
  vrfs:
    - name: default
    
# AAA settings and local users
aaa_settings:
  authorization:
    exec:
      default: local
  local_users:
    - name: arista
      privilege: 15
      role: network-admin
      sha512_password: "{{ ansible_password | password_hash('sha512', salt='arista', rounds=5000) }}"
      ssh_key: "{{ lookup('ansible.builtin.file', '~/.ssh/id_rsa.pub') }}"

# OOB Management network default gateway.
mgmt_gateway: 192.168.0.1
mgmt_interface_vrf: default
mgmt_interface: Management0

# NTP Servers IP or DNS name, first NTP server will be preferred, and sourced from Management VRF
ntp_settings:
  servers:
    - name: 192.168.0.1
      iburst: true

# DNS settings
dns_settings:
  domain: atd.lab
  servers:
    - ip_address: 192.168.0.1

# Point to Point Links MTU Override for Lab
p2p_uplinks_mtu: 1500

# Set IPv4 Underlay Routing and EVPN Overlay Routing to use eBGP
underlay_routing_protocol: ebgp
overlay_routing_protocol: ebgp

# Configure password authentication for BGP peerings
bgp_peer_groups:
  evpn_overlay_peers:
    password: Q4fqtbqcZ7oQuKfuWtNGRQ==
  ipv4_underlay_peers:
    password: 7x4B4rnJhZB438m9+BrBfQ==
  mlag_ipv4_underlay_peer:
    password: 4b21pAdCvWeAqpcKDFMdWw==

# # L3 Edge port definitions. This can be any port in the entire Fabric, where IP interfaces are defined.
# l3_edge:
#   # Define a new IP pool that will be used to assign IP addresses to L3 Edge interfaces.
#   p2p_links_ip_pools:
#     - name: S1_to_S2_IP_pool
#       ipv4_pool: 172.16.255.0/24
#   # Define a new link profile which will match the IP pool, the used ASNs and include the defined interface into underlay routing
#   p2p_links_profiles:
#     - name: S1_to_S2_profile
#       ip_pool: S1_to_S2_IP_pool
#       as: [ 65103, 65203 ]
#       include_in_underlay_protocol: true
#   # Define each P2P L3 link and link the nodes, the interfaces and the profile used.
#   p2p_links:
#     - id: 1
#       nodes: [ s1-brdr1, s2-brdr1 ]
#       interfaces: [ Ethernet4, Ethernet4 ]
#       profile: S1_to_S2_profile
#     - id: 2
#       nodes: [ s1-brdr2, s2-brdr2 ]
#       interfaces: [ Ethernet5, Ethernet5 ]
#       profile: S1_to_S2_profile
